<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName></AssemblyName>
  </PropertyGroup>
  
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <EmbeddedResource Include="Styles\SimpleStyle.axaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Themes.Simple" />
    <PackageReference Include="Avalonia.Markup.Xaml.Loader" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" />
    <PackageReference Include="HeyRed.ImageSharp.Heif" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Pfim" />
    <PackageReference Include="ReactiveUI.Avalonia" />
    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="Svg.Skia" />
    <PackageReference Include="YamlDotNet" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="System.Reactive" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Localization\**\*" Exclude="Localization\convert.py" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="Styles\SimpleStyle.axaml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
