<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <TargetFramework>net10.0-browser1.0</TargetFramework>
    <WasmAllowUndefinedSymbols>true</WasmAllowUndefinedSymbols>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
   <WasmBuildNative>true</WasmBuildNative>
   <RunAOTCompilation>true</RunAOTCompilation>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Browser" />
    <PackageReference Include="Avalonia.Desktop" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PixelArtEditor\PixelArtEditor.csproj" />
  </ItemGroup>
</Project>
